version: '3.8'

services:
  copytop_api:
    build: .
    environment:
      VAPID_PUBLIC_KEY: ${VAPID_PUBLIC_KEY}
      VAPID_PRIVATE_KEY: ${VAPID_PRIVATE_KEY}
    ports:
      - "5001:5001"
    volumes:
      - './app:/Copytop_Api'
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
    networks:
      - mysql-phpmyadmin
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    container_name: db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      #If you change the credentials in the pma, you need to delete your volumes
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin','ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - mysql-phpmyadmin
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Port pour le protocole AMQP
      - "15672:15672" # Port pour l'interface de gestion RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_ERLANG_COOKIE: 'secret_cookie'

volumes:
  dbdata:
  rabbitmq_data:

networks:
  mysql-phpmyadmin:
    name: mysql-phpmyadmin
    # use the bridge driver
    driver: bridge
